'use client';
import { useState, useEffect } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { MessageCircle, X } from 'lucide-react';

interface WhatsAppQRProps {
  phoneNumber: string;
  message?: string;
  businessName?: string;
}

interface UserData {
  id: number;
  name: string;
  email: string;
}

interface QRRecord {
  id: string;
  userId: number | null;
  userName: string;
  userEmail: string;
  phoneNumber: string;
  message: string;
  businessName: string;
  timestamp: string;
  action: 'viewed' | 'generated' | 'clicked';
}

export default function WhatsAppQR({ 
  phoneNumber, 
  message = "Hola, me interesa conocer más sobre sus servicios turísticos en San Rafael",
  businessName = "TourEx San Rafael"
}: WhatsAppQRProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [qrSize, setQrSize] = useState(220);
  const [currentUser, setCurrentUser] = useState<UserData | null>(null);

  // Handle responsive QR size
  useEffect(() => {
    const updateQrSize = () => {
      setQrSize(window.innerWidth < 640 ? 180 : window.innerWidth < 768 ? 220 : 280);
    };
    
    updateQrSize();
    window.addEventListener('resize', updateQrSize);
    return () => window.removeEventListener('resize', updateQrSize);
  }, []);

  // Get current user from localStorage
  useEffect(() => {
    const userData = localStorage.getItem('tourex_user');
    if (userData) {
      try {
        setCurrentUser(JSON.parse(userData));
      } catch (error) {
        console.error('Error parsing user data:', error);
      }
    }
  }, []);

  // Save QR record to localStorage
  const saveQRRecord = (action: 'viewed' | 'generated' | 'clicked') => {
    try {
      const record: QRRecord = {
        id: `qr_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        userId: currentUser?.id || null,
        userName: currentUser?.name || 'Usuario Anónimo',
        userEmail: currentUser?.email || 'no-email',
        phoneNumber,
        message,
        businessName,
        timestamp: new Date().toISOString(),
        action
      };

      // Get existing records
      const existingRecords = JSON.parse(localStorage.getItem('tourex_qr_records') || '[]');
      
      // Add new record
      existingRecords.push(record);
      
      // Keep only last 100 records to avoid storage bloat
      if (existingRecords.length > 100) {
        existingRecords.splice(0, existingRecords.length - 100);
      }
      
      // Save back to localStorage
      localStorage.setItem('tourex_qr_records', JSON.stringify(existingRecords));
      
      console.log('📝 QR Record saved:', {
        action,
        user: currentUser?.name || 'Anónimo',
        timestamp: new Date().toLocaleString()
      });
      
      // Log all records for debugging
      console.log('📄 All QR Records:', existingRecords);
      
    } catch (error) {
      console.error('Error saving QR record:', error);
    }
  };

  // Format phone number (remove spaces, dashes, etc.)
  const cleanPhone = phoneNumber.replace(/\D/g, '');
  
  // Create WhatsApp URL with user tracking
  const createWhatsAppUrl = () => {
    const userInfo = currentUser ? ` - Consulta de ${currentUser.name}` : '';
    const enhancedMessage = message + userInfo;
    return `https://wa.me/${cleanPhone}?text=${encodeURIComponent(enhancedMessage)}`;
  };

  const whatsappUrl = createWhatsAppUrl();

  const handleOpenModal = () => {
    setIsOpen(true);
    saveQRRecord('viewed');
  };

  const handleGenerateQR = () => {
    saveQRRecord('generated');
    console.log('🔄 QR Code generated by:', currentUser?.name || 'Usuario Anónimo');
  };

  const handleWhatsAppClick = () => {
    saveQRRecord('clicked');
    console.log('📱 WhatsApp link clicked by:', currentUser?.name || 'Usuario Anónimo');
  };

  // Generate QR on component mount and when opened
  useEffect(() => {
    if (isOpen) {
      handleGenerateQR();
    }
  }, [isOpen]);

  return (
    <>
      {/* Floating QR Button - Better Responsive */}
      <div className="fixed bottom-4 right-4 sm:bottom-6 sm:right-6 z-50">
        <button
          onClick={handleOpenModal}
          className="bg-green-500 hover:bg-green-600 text-white p-3 sm:p-4 md:p-5 rounded-full shadow-2xl transition-all duration-300 hover:scale-110 group animate-pulse hover:animate-none"
          title="Contactar por WhatsApp"
        >
          <MessageCircle className="w-6 h-6 sm:w-8 sm:h-8 md:w-10 md:h-10" />
          <div className="absolute -top-12 -left-16 sm:-top-14 sm:-left-20 md:-left-24 bg-black text-white text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-2 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap shadow-lg">
            📱 Contactar por WhatsApp
            {currentUser && (
              <div className="text-xs opacity-75">Como: {currentUser.name}</div>
            )}
            <div className="absolute top-full left-1/2 transform -translate-x-1/2 w-0 h-0 border-l-4 border-r-4 border-t-4 border-transparent border-t-black"></div>
          </div>
        </button>
      </div>

      {/* QR Modal - Better Responsive and Spacing */}
      {isOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-60 z-50 flex items-center justify-center p-3 sm:p-4 backdrop-blur-sm">
          <div className="bg-white rounded-2xl sm:rounded-3xl p-4 sm:p-6 md:p-8 max-w-sm sm:max-w-md md:max-w-lg w-full mx-2 sm:mx-4 relative shadow-2xl max-h-[95vh] overflow-y-auto">
            {/* Close Button */}
            <button
              onClick={() => setIsOpen(false)}
              className="absolute top-3 right-3 sm:top-4 sm:right-4 md:top-6 md:right-6 text-gray-500 hover:text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-full p-1.5 sm:p-2 transition-colors z-10"
            >
              <X className="w-4 h-4 sm:w-5 sm:h-5 md:w-6 md:h-6" />
            </button>

            {/* Header with User Info */}
            <div className="text-center mb-6 sm:mb-8 pt-8 sm:pt-4">
              <div className="flex items-center justify-center gap-2 sm:gap-3 mb-3 sm:mb-4">
                <div className="bg-green-100 p-2 sm:p-3 rounded-full">
                  <MessageCircle className="w-8 h-8 sm:w-10 sm:h-10 md:w-12 md:h-12 text-green-500" />
                </div>
              </div>
              <h3 className="text-xl sm:text-2xl md:text-3xl font-bold text-gray-800 mb-2">{businessName}</h3>
              <p className="text-gray-600 text-xs sm:text-sm md:text-base leading-relaxed px-2">
                Escanea el código QR con tu teléfono para contactarnos directamente por WhatsApp
              </p>
              {currentUser && (
                <div className="mt-3 p-2 bg-blue-50 rounded-lg">
                  <p className="text-xs text-blue-700">
                    👤 Generado por: <strong>{currentUser.name}</strong>
                  </p>
                </div>
              )}
            </div>

            {/* QR Code - Responsive Size */}
            <div className="flex justify-center mb-6 sm:mb-8 p-4 sm:p-6 md:p-8 bg-gradient-to-br from-gray-50 to-gray-100 rounded-xl sm:rounded-2xl shadow-inner">
              <div className="bg-white p-2 sm:p-3 md:p-4 rounded-lg sm:rounded-xl shadow-lg">
                <QRCodeSVG
                  value={whatsappUrl}
                  size={qrSize}
                  bgColor="#ffffff"
                  fgColor="#000000"
                  level="M"
                  includeMargin={true}
                />
              </div>
            </div>

            {/* Instructions - Better Spacing */}
            <div className="space-y-3 sm:space-y-4 mb-6 sm:mb-8">
              <div className="flex items-start gap-3 sm:gap-4 p-2 sm:p-3 bg-green-50 rounded-lg sm:rounded-xl">
                <div className="bg-green-500 text-white rounded-full w-6 h-6 sm:w-8 sm:h-8 md:w-10 md:h-10 flex items-center justify-center text-xs sm:text-sm md:text-base font-bold flex-shrink-0">
                  1
                </div>
                <div className="pt-0.5">
                  <p className="text-xs sm:text-sm md:text-base text-gray-700 font-medium">
                    📱 Abre la cámara o WhatsApp
                  </p>
                  <p className="text-xs sm:text-xs md:text-sm text-gray-500 mt-0.5">
                    Usa la cámara de tu teléfono o la función de escanear QR en WhatsApp
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-3 sm:gap-4 p-2 sm:p-3 bg-blue-50 rounded-lg sm:rounded-xl">
                <div className="bg-blue-500 text-white rounded-full w-6 h-6 sm:w-8 sm:h-8 md:w-10 md:h-10 flex items-center justify-center text-xs sm:text-sm md:text-base font-bold flex-shrink-0">
                  2
                </div>
                <div className="pt-0.5">
                  <p className="text-xs sm:text-sm md:text-base text-gray-700 font-medium">
                    🎯 Apunta al código QR
                  </p>
                  <p className="text-xs sm:text-xs md:text-sm text-gray-500 mt-0.5">
                    Centra el código en tu pantalla y mantén firme el teléfono
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-3 sm:gap-4 p-2 sm:p-3 bg-purple-50 rounded-lg sm:rounded-xl">
                <div className="bg-purple-500 text-white rounded-full w-6 h-6 sm:w-8 sm:h-8 md:w-10 md:h-10 flex items-center justify-center text-xs sm:text-sm md:text-base font-bold flex-shrink-0">
                  3
                </div>
                <div className="pt-0.5">
                  <p className="text-xs sm:text-sm md:text-base text-gray-700 font-medium">
                    🚀 ¡Conecta con nosotros!
                  </p>
                  <p className="text-xs sm:text-xs md:text-sm text-gray-500 mt-0.5">
                    Se abrirá automáticamente nuestro chat de WhatsApp
                  </p>
                </div>
              </div>
            </div>

            {/* Alternative Button - Better Responsive */}
            <div className="text-center">
              <p className="text-xs sm:text-sm md:text-base text-gray-500 mb-3 sm:mb-4">¿No puedes escanear? No hay problema:</p>
              <a
                href={whatsappUrl}
                target="_blank"
                rel="noopener noreferrer"
                onClick={handleWhatsAppClick}
                className="inline-flex items-center gap-2 sm:gap-3 bg-gradient-to-r from-green-500 to-green-600 hover:from-green-600 hover:to-green-700 text-white px-4 sm:px-6 md:px-8 py-2.5 sm:py-3 md:py-4 rounded-lg sm:rounded-xl transition-all duration-300 text-sm sm:text-base md:text-lg font-semibold shadow-lg hover:shadow-xl transform hover:-translate-y-1"
              >
                <MessageCircle className="w-4 h-4 sm:w-5 sm:h-5 md:w-6 md:h-6" />
                Abrir WhatsApp
              </a>
              <p className="text-xs sm:text-xs md:text-sm text-gray-400 mt-2 sm:mt-3">
                Se abrirá en una nueva ventana
              </p>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
